---

- hosts: all
  become: true
  tasks:

  - name: update repo and install apache package and php
    package:
      name: 
        - "{{apache_package}}"
        - "{{php_package}}"  
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: instal centos
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
