---

- hosts: all
  become: true
  pre_tasks:
  - name: install updates Centos
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: instal updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:
  - name: update repo and install apache package and php
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{apache_package}}"
        - "{{php_package}}"  
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: instal centos
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"



- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package
    tags: mariadb,db,ubuntu
    package:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"



- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: ubuntu,samba
    package:
      name:
        - samba
      state: latest
    when: ansible_distribution == "Ubuntu"      
